nameOverride:
fullnameOverride:

image:
  repository: busybox
  tag: stable
  pullPolicy: IfNotPresent

replicaCount: 1 
activeProfile: "dev"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

service:
  type: ClusterIP

ingress:
  enabled: true
  host: "default.host"
