apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
data:
  config.json: |
    {
      "hello": "world",
      "message": "Sample JSON for config"
    }
