apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
type: Opaque
data:
  {{ randAlphaNum 8 }}: {{ randAlphaNum 16 | b64enc }}
  {{ randAlphaNum 8 }}: {{ randAlphaNum 16 | b64enc }}
