apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: logs
      port: 8081
      targetPort: 8081
    - name: soap
      port: 8082
      targetPort: 8082
