apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
spec:
  generators:
    - list:
        elements:
          - name: dev
            cluster: dev-global-cluster-0
            url: https://kubernetes.default.svc
            valuesFile: https://raw.githubusercontent.com/mpietrzak384/spring-boot-api-argocd/refs/heads/main/envs/dev-values.yaml
            namespace: spring-boot-api-dev
          - name: prd
            cluster: prd-global-cluster-5
            url: https://kubernetes.default.svc
            valuesFile: https://raw.githubusercontent.com/mpietrzak384/spring-boot-api-argocd/refs/heads/main/envs/prd-values.yaml
            namespace: spring-boot-api-prd
  template:
    metadata:
      name: '{{name}}-spring-boot-api'
    spec:
      project: spring-boot-api
      source:
        repoURL: 'https://github.com/mpietrzak384/spring-boot-api-argocd.git'
        targetRevision: HEAD
        path: chart
        helm:
          releaseName: alpha
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true